version: '3.7'

#Microservico
services:
  app-server:
    build:
      context: consumer-rabbitmq
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    restart: always
    depends_on: 
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rabbitmq?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql

#MySql
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: rabbitmq
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql 

#RabbitMQ
  rabbitmq:
    image: "rabbitmq:3-management"
       
# Volumes
volumes:
  db-data: