version: '3.7'

#Microservico
services:
  app-server:
    build:
      context: consumer-rabbitmq
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    depends_on: 
      - db
      - rabbitmq
    network_mode: "host"

#MySql
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: rabbitmq
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql 

#RabbitMQ
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
       - 5672:5672
       - 15672:15672   
       
# Volumes
volumes:
  db-data: