version: '3.7'
services:

#  publisher:
#    build: publisher-rabbitmq/
#    ports:
#      - "8080:8080"
#    depends_on:
#      - rabbitmq
#    network_mode: "host"
    
  consumer:
    build: .
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      #RABBITMQ
      - RABBITMQ_HOST=localhost
      - RABBITMQ_VHOST=/
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      #MYSQL
      - JDBC_URL=jdbc:mysql://localhost:3306/rabbitmq?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      #QUEUE
      - INSERTION_QUEUE=insertion.queue
      - VALIDATION_QUEUE=validation.queue
      - RESPONSE_EXCHANGE=response.exchange
      - RESPONSE_QUEUE=response.queue
      - RESPONSE_ROUTING_KEY=response.key
      
    depends_on:
      - rabbitmq
      - db
    network_mode: "host"
    
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
      
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rabbitmq
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    #volumes:
    # - ./database:/var/lib/mysql